"""Constants for the game model."""

STEP_MAX = 750
VIEWPORT_PIXELS = 128

# the y coordinate where the game viewport starts (above which is the HUD)
GAMEPLAY_START_Y = 56

LOCATION_CHANGE_COOLDOWN = 8
MOVEMENT_FRAMES = 6
ATTACK_COOLDOWN = 15
ITEM_COOLDOWN = 10
CAVE_COOLDOWN = 60
RANDOM_DELAY_MAX_FRAMES = 1
RESET_DELAY_MAX_FRAMES = 60
